version: '3.8'

services:
  api:
    build: .
    container_name: pump-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pump
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    networks:
      - pump-network

  db:
    image: postgres:15-alpine
    container_name: pump-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pump
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pump-network

  nginx:
    image: nginx:alpine
    container_name: pump-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    depends_on:
      - api
      - certbot
    networks:
      - pump-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    networks:
      - pump-network


networks:
  pump-network:
    driver: bridge

volumes:
  postgres_data:
