version: '3.8'

services:
  api:
    build: .
    container_name: pump-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PINATA_JWT=${PINATA_JWT}
    volumes:
      - ./app:/app/app
    networks:
      - pump-network

  nginx:
    image: nginx:alpine
    container_name: pump-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    depends_on:
      - api
      - certbot
    networks:
      - pump-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/html

networks:
  pump-network:
    driver: bridge 